on:
  push: {}
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'


jobs:
 test_job:
   runs-on: [ self-hosted, Linux, X64, Ubuntu ]
   name: A job to test
   steps:
     - uses: actions/checkout@v2
     - id: test
       uses: bayaro/test-action-01@master
       with:
         test-var: 'tests v0.0.1 '
     - run: echo random-number ${{ steps.test.outputs.random-number }}
       shell: bash
