name: "main.yaml"

on:
  push:
    name: "on push"
  workflow_dispatch:
    name: manual
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'Pipiline 01'


jobs:
  call-action-01:
    uses: bayaro/test-action-01/.github/workflows/action-01.yaml@master

  test_job:
    name: A job to test
    needs: call-action-01
    runs-on: ubuntu-latest
    steps:
      - run: echo random-number ${{ steps.test.outputs.random-number }}
        shell: bash
