name: "main.yaml"

on:
  push:
    name: "on push"
  workflow_dispatch:
    name: manual
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Jessica'
      home:
        description: 'location'
        required: false
        default: 'Pipiline 01'


jobs:
  call-action-01:
    uses: bayaro/test-action-01/.github/workflows/action-01.yaml@master
    with:
      home: ${{ github.event.inputs.home }}
      name: ${{ github.event.inputs.name }}

  test_job:
    name: A job to test
    needs: call-action-01
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo random-number ${{ steps.test.outputs.random-number }}
          echo ${{ needs.call-action-01.outputs.output1 }}
        shell: bash
